# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  A study of the application of artificial intelligence to solving problems in robotics. 
  Topics include subsumption, planning, machine learning, vision, neural networks, 
  localization, and mapping. Students configure provided implementations of algorithms 
  to control physical robots.
baseurl: "/csci235" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

number: CSCI 235
title: Intelligent Robotics
semester: Spring 2023

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Resources
        url: '#resources'
  - page: Calendar
    url: '#calendar'
  - title: Assessment
    subfolderitems:
    - page: Projects
      url: '#projects'
    - page: Final Project
      url: '#finalproject'
    - page: Participation
      url: '#participation'
    - page: Specifications Grading
      url: '#grading'
    - page: Late Days
      url: '#latedays'
  - page: Equipment
    url: '#equipment'
  - page: Commitments
    url: '#commitments'

instructors:
  - id: ferrer
    name: Dr. Gabriel Ferrer
    email: ferrer@hendrix.edu
    web: http://ozark.hendrix.edu/~ferrer
    phone: (501) 450-3879
    officehours: https://drferrer.youcanbook.me/

offerings:
  - name: LECTURE 01
    loc: MCREY 115
    time: TR 8:15am - 9:30am
    instructor: ferrer

resources:
  - name: Mindstorms Education EV3 MicroPython
  image: assets/images/Lego_education.png
    url: https://pybricks.com/ev3-micropython/
    
extra-resources:
  - name: "How to Think Like a Computer Scientist: Interactive Edition"
    image: assets/images/runestone_logo.png
    url: https://runestone.academy/runestone/books/published/thinkcspy/index.html
  - name: Python Tutor
    image: assets/images/python_tutor.png
    url: http://pythontutor.com/
  - name: CodingBat Python
    image: assets/images/codingbat.jpg
    url: https://codingbat.com/python
  - name: CheckiO Python Practice
    image: assets/images/checkio_logo_small.png
    url: https://py.checkio.org/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
